name = "staging-techseovitals-com"
main = "worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

# Serve static files from the _site directory
[site]
bucket = "./_site"

# Build configuration
[build]
command = "npm run build"

# Production environment
[env.production]
workers_dev = false
routes = [
  { pattern = "techseovitals.com/*", zone_name = "techseovitals.com" },
  { pattern = "www.techseovitals.com/*", zone_name = "techseovitals.com" }
]

# Staging environment
[env.staging]
workers_dev = true

# Compatibility flags for better Node.js compatibility
compatibility_flags = ["nodejs_compat"]