name = "staging-techseovitals-com"
main = "worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

# Static assets configuration
[assets]
directory = "./_site"

# Build configuration
[build]
command = "npm run build"

# Production environment
[env.production]
workers_dev = false
routes = [
  { pattern = "staging.techseovitals.com/*", zone_name = "techseovitals.com" }
]

# Compatibility flags for better Node.js compatibility
compatibility_flags = ["nodejs_compat"]