name = "techseovitals-contact-form"
main = "worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[env.production.vars]
# Set RESEND_API_KEY in Cloudflare Dashboard or via CLI:
# wrangler secret put RESEND_API_KEY

[env.development.vars]
# For local development, you can set variables here or use .env file

# Custom domain routing (optional - configure in Cloudflare Dashboard)
# routes = [
#   { pattern = "techseovitals.com/api/contact", zone_name = "techseovitals.com" }
# ]

# Worker settings
[limits]
cpu_ms = 50